name: Build X86_64
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: wulan17/debian:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: bash ci.sh deps
    - name: Build LLVM
      run: bash ci.sh llvm
    - name: Build binutils
      run: bash ci.sh binutils
    - name: Compress artifacts
      run: bash ci.sh compress
    - uses: actions/upload-artifact@v4
      with:
        name: clang-bookworm
        path: dist/
