name: Build X86_64 (Archlinux)
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: bash ci-arch.sh deps
    - name: Build LLVM
      run: bash ci-arch.sh llvm
    - name: Build binutils
      run: bash ci-arch.sh binutils
    - name: Compress artifacts
      run: bash ci-arch.sh compress
    - uses: actions/upload-artifact@v4
      with:
        name: clang-aarch64
        path: dist/
