name: Build AArch64
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04-arm
    container:
      image: arm64v8/debian:bookworm
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: bash ci-aarch64.sh deps
    - name: Build LLVM
      run: bash ci-aarch64.sh llvm
    - name: Build binutils
      run: bash ci-aarch64.sh binutils
    - name: Compress artifacts
      run: bash ci.sh compress
    - uses: actions/upload-artifact@v4
      with:
        name: clang-bookworm-aarch64
        path: dist/
